### PR TITLE
import dashboards function

### PR DESCRIPTION
**Pull request by nogreintel**
Added function to import json dashboards into superset based on the api `POST /dashboard/import/`.

Currently only works for dashboards, although might be expandable to chart/dataset imports.

Please feel free to modify, rename, implement whatever tests you see fit; alternatively, if there's anything I can do, let me know.

Thanks!

### CODE REVIEW

**Comment by opus-42** [comment]
Hello @nogreintel : is there something I can merge or if you want to add the functionality ? Or did you rollback your feature ? I see that the pull request has been closed.

**Comment by nogreintel** [comment]
Sorry, about this. I had to close the pull request for a moment. Now it's all good to go. Thank you.

**Comment by nogreintel** [comment]
Bump. Let me know if you need anything, or have any feedback.

**Comment by opus-42** [comment]
Thank you for your contribution, this has been merged

**Pull request merged**
