### PR TITLE
Fix Load Balancer problems

### PR DESCRIPTION
**Pull request by mandruis7**
Seems that infront of a load balancer that modifies http to https requires the endpoints and urls to always end in "/".
This might require more fixes in the future

### CODE REVIEW

**Comment by opus-42** [comment]
Is it equivalent for the superset API that we pass for example `/security/csrf_token` or `/security/csrf_token/` ?

**Comment by mandruis7** [comment]
Yes, It's exactly the same endpoint just that seems that when you're proxing the pod with an LB or NGINX doesn't admit `/security/csrf_token` just `/security/csrf_token/` here's the documentation that specifies always a "/" at the end https://superset.apache.org/docs/api/

**Comment by ecederstrand** [comment]
The actual URL is `/security/csrf_token/`. SuperSet in a standard config will redirect this client from `/security/csrf_token` to `/security/csrf_token/` automatically but it generates an unnecessary request.

**Review by opus-42 — APPROVED** [review]

**Comment by opus-42** [comment]
This has been merged ! Thanks @manueliglesiasgarcia @ecederstrand

**Pull request merged**
